name: Free Disk Space on Linux
description: Remove unneeded files from the Ubuntu GitHub runner.

runs:
  using: composite
  steps:
    - shell: bash
      if: ${{ runner.os == 'Linux' }}
      run: |-
        sudo swapoff -a
        sudo rm -rf /swapfile /usr/share/dotnet /usr/local/lib/android /opt/ghc "$ANDROID_HOME" /usr/local/.ghcup /usr/local/share/powershell /opt/az /opt/microsoft /etc/skel
        docker rmi $(docker images -q) -f
