name: Test patches
on:
  push:

env:
  # Bump this number to invalidate the GH actions cache
  cache-version: 0

jobs:
  test-ghc-patches:
    name: Test GHC patches
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        ghc-version:
          - '9.4.3'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Mount Bazel cache
        uses: actions/cache@v3
        with:
          path: ~/repo-cache
          key: repo-cache-${{ runner.os }}-bindist-${{ env.cache-version }}
      - name: Install Bazel
        shell: bash
        run: |
          BAZEL_DIR="$(.ci/fetch-bazel-bindist)"
          mv $BAZEL_DIR $HOME/bazel
      - name: Configure
        env:
          BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}
        shell: bash
        run: |
          # Avoid failures of the form `deadline exceeded after 14999958197ns DEADLINE_EXCEEDED`.
          # See https://github.com/tweag/rules_haskell/issues/1498 and https://github.com/tweag/rules_haskell/pull/1692.
          [[ ${{ runner.os }} == Linux ]] && sudo sysctl -w net.ipv4.tcp_keepalive_time=60
          case ${{ runner.os }} in
            macOS) BUILD_CONFIG=ci-macos-bindist;;
            Linux) BUILD_CONFIG=ci-linux-bindist;;
            Windows) BUILD_CONFIG=ci-windows-bindist;;
          esac
          cat >.bazelrc.local <<EOF
          common --config=ci
          build --config=$BUILD_CONFIG
          build --remote_header=x-buildbuddy-api-key="$BUILDBUDDY_API_KEY"
          EOF
          cat >~/.netrc <<EOF
          machine api.github.com
                  password ${{ secrets.GITHUB_TOKEN }}
          EOF
      - name: Build & test
        shell: bash
        run: |
          export PATH=$HOME/bazel:$PATH
          [[ ${{ runner.os }} == macOS ]] && export BAZEL_USE_CPP_ONLY_TOOLCHAIN=1
          export GHC_VERSION=${{ matrix.ghc-version }}
          ./tests/run-start-script.sh --use-bindists
