name: Continuous integration
on:
  push:
  workflow_dispatch: # allows manual triggering
env:
  # Bump this number to invalidate the GH actions cache
  cache-version: 0

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  test-nixpkgs:
    name: Build & Test - Nixpkgs
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, macos-latest]
        module: [rules_haskell_tests]
        bzlmod: [false]
        ghc:
          - 9.6.2
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/free_disk_space_on_linux
      - name: Mount Bazel cache
        uses: actions/cache@v3
        with:
          path: ~/repo-cache
          key: repo-cache-${{ runner.os }}-nixpkgs-${{ env.cache-version }}
      - uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=./nixpkgs/default.nix
          extra_nix_config: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
            extra-substituters = https://cache.iog.io
      - uses: tweag/configure-bazel-remote-cache-auth@v0
        with:
          buildbuddy_api_key: ${{ secrets.BUILDBUDDY_API_KEY }}
          bazelrc_path: .bazelrc.auth
      - uses: ./.github/actions/set_tcp_keepalive_time
      - uses: ./.github/actions/authenticate_github_api
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure
        run: |
          case ${{ runner.os }} in
            macOS) BUILD_CONFIG=ci-macos-nixpkgs;;
            Linux) BUILD_CONFIG=ci-linux-nixpkgs;;
          esac
          cat >>.bazelrc.local <<EOF
          common --config=ci
          build --config=$BUILD_CONFIG
          common --enable_bzlmod=${{ matrix.bzlmod }}
          EOF
          cp .bazelrc.local rules_haskell_nix
          cp .bazelrc.local rules_haskell_tests
      - name: Check Bazel version
        run: |
          nix-shell --arg docTools false --argstr ghcVersion ${{ matrix.ghc }} --pure --run .ci/check-bazel-version
      - name: Build & test - rules_haskell
        if: matrix.module == 'rules_haskell'
        run: |
          nix-shell --arg docTools false --argstr ghcVersion ${{ matrix.ghc }} --pure --run '
            set -euo pipefail
            bazel test //...
            bazel build //docs:api_html
            bazel build //docs:guide_html
            '
      - name: Build & test - rules_haskell_nix
        if: matrix.module == 'rules_haskell_nix'
        run: |
          nix-shell --arg docTools false --argstr ghcVersion ${{ matrix.ghc }} --pure --run '
            set -euo pipefail
            cd rules_haskell_nix
            bazel test //...
            '
      - name: Build & test - rules_haskell_tests
        if: matrix.module == 'rules_haskell_tests'
        run: |
          nix-shell --arg docTools false --argstr ghcVersion ${{ matrix.ghc }} --pure --run '
            set -euo pipefail
            cd rules_haskell_tests
            bazel test //tests/haskell_module/dep-narrowing-th:Test
            '

  test-bindist:
    name: Build & Test - bindist
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, macos-latest]
        module: [rules_haskell_tests]
        bzlmod: [false]
        ghc:
          - 9.6.2
    env:
      # prevent auto-detection of system compilers on Windows
      BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN: ${{ matrix.os == 'windows-latest' && 1 || 0 }}
      # do not use Xcode on macOS
      BAZEL_USE_CPP_ONLY_TOOLCHAIN: 1
      GHC_VERSION: ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/free_disk_space_on_linux
      - uses: ./.github/actions/install_apt_pkgs
        with:
          packages: libtinfo5
      - name: Mount Bazel cache
        uses: actions/cache@v3
        with:
          path: ~/repo-cache
          key: repo-cache-${{ runner.os }}-bindist-${{ env.cache-version }}
      - name: Install Bazel
        shell: bash
        run: |
          BAZEL_DIR="$(.ci/fetch-bazel-bindist)"
          mv $BAZEL_DIR $HOME/bazel
          echo "$HOME/bazel" >> "$GITHUB_PATH"
      - uses: tweag/configure-bazel-remote-cache-auth@v0
        with:
          buildbuddy_api_key: ${{ secrets.BUILDBUDDY_API_KEY }}
          bazelrc_path: .bazelrc.auth
      - uses: ./.github/actions/set_tcp_keepalive_time
      - uses: ./.github/actions/authenticate_github_api
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure
        shell: bash
        run: |
          case "${{ runner.os }},${{ matrix.module }}" in
            macOS,*) BUILD_CONFIG=ci-macos-bindist;;
            Linux,*) BUILD_CONFIG=ci-linux-bindist;;
            Windows,rules_haskell) BUILD_CONFIG=ci-windows-bindist-rules-haskell;;
            Windows,rules_haskell_tests) BUILD_CONFIG=ci-windows-bindist-rules-haskell-tests;;
          esac
          if [[ ${{ runner.os }} == Windows ]]; then
              output_root_setting="startup --output_user_root=C:/_bzl"
              # On windows, we use a separate remote cache for bzlmod,
              # because the c dependency analysis is leaking absolute paths which are different
              if ${{ matrix.bzlmod }}; then
                bzlmod_cache_silo_key='build --remote_default_exec_properties=bzlmod-cache-silo-key=bzlmod'
              else
                bzlmod_cache_silo_key='build --remote_default_exec_properties=bzlmod-cache-silo-key=workspace'
              fi
          else
              output_root_setting=""
              bzlmod_cache_silo_key=""
          fi
          cat >>.bazelrc.local <<EOF
          common --config=ci
          build --config=$BUILD_CONFIG
          $output_root_setting
          $bzlmod_cache_silo_key
          common --enable_bzlmod=${{ matrix.bzlmod }}
          EOF
          cp .bazelrc.local rules_haskell_tests
      - name: Build & test - rules_haskell
        if: matrix.module == 'rules_haskell'
        shell: bash
        run: |
          # Quote the package specifier so that it works on Windows
          bazel test "//..."

      - name: Build & test - rules_haskell_tests
        if: matrix.module == 'rules_haskell_tests'
        shell: bash
        run: |
          cd rules_haskell_tests
          bazel test //tests/haskell_module/dep-narrowing-th:Test

      - name: Collect Logs
        id: collect_logs
        if: failure()
        shell: bash
        run: |
          mkdir -p logs
          if [[ ${{ matrix.module }} == 'rules_haskell_tests' ]]; then
             dir=rules_haskell_tests
          else
             dir=.
          fi
          base=$( cd "$dir" ; bazel info output_base )
          find "$base" -mindepth 1 -maxdepth 1 -name "java*.log.*" -print0 | xargs -0rI % cp % logs/

      - name: Upload Logs
        if: ${{ failure() && steps.collect_logs.conclusion == 'success' }}
        uses: actions/upload-artifact@v3
        with:
          name: Logs ${{ matrix.os }} ${{ matrix.module }} ${{ matrix.bzlmod }}
          path: logs
