name: Continuous integration
on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch: # allows manual triggering
env:
  # Bump this number to invalidate the GH actions cache
  cache-version: 0

jobs:
  test-bindist:
    name: Build & Test - bindist
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |-
          sudo swapoff -a
          sudo rm -rf /swapfile /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo apt-get update
          sudo apt-get install --no-install-recommends -yy libtinfo5
          sudo apt clean
          docker rmi $(docker images -q) -f
      - uses: actions/checkout@v3
      - name: Mount Bazel cache
        uses: actions/cache@v3
        with:
          path: ~/repo-cache
          key: repo-cache-${{ runner.os }}-bindist-${{ env.cache-version }}
      - name: Install Bazel
        shell: bash
        run: |
          BAZEL_DIR="$(.ci/fetch-bazel-bindist)"
          mv $BAZEL_DIR $HOME/bazel
      - name: Configure
        env:
          BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}
        shell: bash
        run: |
          # Avoid failures of the form `deadline exceeded after 14999958197ns DEADLINE_EXCEEDED`.
          # See https://github.com/tweag/rules_haskell/issues/1498 and https://github.com/tweag/rules_haskell/pull/1692.
          [[ ${{ runner.os }} == Linux ]] && sudo sysctl -w net.ipv4.tcp_keepalive_time=60
          case ${{ runner.os }} in
            macOS) BUILD_CONFIG=ci-macos-bindist;;
            Linux) BUILD_CONFIG=ci-linux-bindist;;
            Windows) BUILD_CONFIG=ci-windows-bindist;;
          esac
          if [ -z "$BUILDBUDDY_API_KEY" ]; then
              cache_setting='--noremote_upload_local_results'
          else
              cache_setting="--remote_header=x-buildbuddy-api-key=$BUILDBUDDY_API_KEY"
          fi
          cat >.bazelrc.local <<EOF
          common --config=ci
          build --config=$BUILD_CONFIG
          build $cache_setting
          EOF
          cat >~/.netrc <<EOF
          machine api.github.com
                  password ${{ secrets.GITHUB_TOKEN }}
          EOF
      - name: Build & test
        shell: bash
        run: |
          export PATH=$HOME/bazel:$PATH
          [[ ${{ runner.os }} == macOS ]] && export BAZEL_USE_CPP_ONLY_TOOLCHAIN=1
          ./tests/run-start-script.sh --use-bindists
          if [[ ${{ runner.os }} == Windows ]]; then
            # On Windows `//...` expands to `/...`.
            bazel build @ghcide//:ghcide
          else
            bazel test //...
          fi
          # Test stack_snapshot pinning
          # NOTE keep in sync with tests/RunTests.hs
          bazel run @stackage-pinning-test-unpinned//:pin
          bazel build @stackage-pinning-test//:hspec
